name: Deploy Tenzies App to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'tenzies/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for Tenzies
        run: |
          cd tenzies
          npm install
        env:
          CI: true

      - name: Build Tenzies app
        run: |
          cd tenzies
          npm run build
         

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tenzies/dist
          destination_dir: tenzies
         
         
         